[package]
name = "lameboy"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
bitflags = "2.9.0"
bytemuck = "1.22.0"
cgmath = "0.18.0"
image = "0.25.6"
pollster = "0.4.0"
wgpu = "25.0.0"
winit = "0.30.9"

[lints.rust]
dead-code = "allow"
